-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.calendar_dim
(
    date_id date NOT NULL,
    week_of_year integer,
    day_of_year integer,
    day_of_week text COLLATE pg_catalog."default",
    month_num integer,
    day_type text COLLATE pg_catalog."default",
    month_name text COLLATE pg_catalog."default",
    month_short text COLLATE pg_catalog."default",
    quarter integer,
    year integer,
    year_quarter text COLLATE pg_catalog."default",
    month_year text COLLATE pg_catalog."default",
    CONSTRAINT calendar_dim_pkey PRIMARY KEY (date_id)
);

CREATE TABLE IF NOT EXISTS public.database_cleaned
(
    index bigint,
    time_bucket timestamp without time zone,
    hub_in_out text COLLATE pg_catalog."default",
    location__monthly_ped_report text COLLATE pg_catalog."default",
    zone_number bigint,
    count double precision
);

ALTER TABLE IF EXISTS public.database_cleaned
    ADD FOREIGN KEY (time_bucket)
    REFERENCES public.calendar_dim (date_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;